/* Shared demo menu items for mock data */

export interface MenuItem {
  id: string;
  name: string;
  description: string;
  category: 'appetizer' | 'main' | 'dessert' | 'beverage' | 'special';
  price: number;
  isAvailable: boolean;
  isPopular?: boolean;
  isVeg?: boolean;
  isSpicy?: boolean;
  calories?: number;
  prepTime?: number;
  image: string;
}

export const DEMO_ITEMS: MenuItem[] = [
  /* Appetizers */
  {
    id: '1',
    name: 'Bruschetta al Pomodoro',
    description: 'Grilled sourdough with fresh tomatoes, garlic, basil and extra-virgin olive oil',
    category: 'appetizer',
    price: 8.99,
    isAvailable: true,
    isPopular: true,
    isVeg: true,
    calories: 220,
    prepTime: 8,
    image: 'https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=400&h=300&fit=crop',
  },
  {
    id: '2',
    name: 'Caesar Salad',
    description: 'Crisp romaine, aged parmesan, house-made Caesar dressing, croutons',
    category: 'appetizer',
    price: 10.99,
    isAvailable: true,
    isVeg: true,
    calories: 310,
    prepTime: 10,
    image: 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?w=400&h=300&fit=crop',
  },
  {
    id: '3',
    name: 'Calamari Fritti',
    description: 'Crispy fried squid rings with marinara dipping sauce and lemon wedge',
    category: 'appetizer',
    price: 13.99,
    isAvailable: true,
    isSpicy: false,
    calories: 420,
    prepTime: 12,
    image: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=400&h=300&fit=crop',
  },
  {
    id: '4',
    name: 'Mushroom Soup',
    description: 'Creamy wild mushroom bisque with truffle oil and chives',
    category: 'appetizer',
    price: 9.5,
    isAvailable: true,
    isVeg: true,
    calories: 280,
    prepTime: 6,
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=400&h=300&fit=crop',
  },
  {
    id: '5',
    name: 'Chicken Wings',
    description: 'Crispy wings tossed in buffalo sauce, served with blue cheese dip',
    category: 'appetizer',
    price: 14.99,
    isAvailable: true,
    isSpicy: true,
    calories: 580,
    prepTime: 15,
    image: 'https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=400&h=300&fit=crop',
  },
  /* Mains */
  {
    id: '6',
    name: 'Grilled Salmon',
    description: 'Atlantic salmon with lemon butter, asparagus and herb rice',
    category: 'main',
    price: 28.99,
    isAvailable: true,
    isPopular: true,
    calories: 620,
    prepTime: 20,
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=400&h=300&fit=crop',
  },
  {
    id: '7',
    name: 'Ribeye Steak',
    description: '12oz premium cut with garlic mashed potatoes and seasonal vegetables',
    category: 'main',
    price: 42.99,
    isAvailable: true,
    isPopular: true,
    calories: 890,
    prepTime: 25,
    image: 'https://images.unsplash.com/photo-1600891964092-4316c288032e?w=400&h=300&fit=crop',
  },
  {
    id: '8',
    name: 'Truffle Pasta',
    description: 'Handmade fettuccine with black truffle cream and parmesan',
    category: 'main',
    price: 24.99,
    isAvailable: true,
    isVeg: true,
    calories: 720,
    prepTime: 18,
    image: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=400&h=300&fit=crop',
  },
  {
    id: '9',
    name: 'Chicken Parmesan',
    description: 'Breaded chicken breast with marinara, mozzarella and spaghetti',
    category: 'main',
    price: 22.99,
    isAvailable: true,
    calories: 780,
    prepTime: 22,
    image: 'https://images.unsplash.com/photo-1574864253938-378d247a5c49?w=400&h=300&fit=crop',
  },
  {
    id: '10',
    name: 'Seafood Platter',
    description: 'Grilled prawns, scallops, mussels and fish with garlic butter',
    category: 'main',
    price: 38.99,
    isAvailable: true,
    isPopular: true,
    calories: 540,
    prepTime: 28,
    image: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=400&h=300&fit=crop',
  },
  /* Desserts */
  {
    id: '11',
    name: 'Chocolate Lava Cake',
    description: 'Warm chocolate cake with molten center, vanilla ice cream',
    category: 'dessert',
    price: 12.99,
    isAvailable: true,
    isPopular: true,
    isVeg: true,
    calories: 520,
    prepTime: 15,
    image: 'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=400&h=300&fit=crop',
  },
  {
    id: '12',
    name: 'Tiramisu',
    description: 'Classic Italian dessert with espresso-soaked ladyfingers',
    category: 'dessert',
    price: 10.99,
    isAvailable: true,
    isVeg: true,
    calories: 450,
    prepTime: 5,
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400&h=300&fit=crop',
  },
  {
    id: '13',
    name: 'Panna Cotta',
    description: 'Vanilla bean panna cotta with berry compote',
    category: 'dessert',
    price: 9.99,
    isAvailable: true,
    isVeg: true,
    calories: 380,
    prepTime: 5,
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&h=300&fit=crop',
  },
  /* Beverages */
  {
    id: '14',
    name: 'Fresh Lemonade',
    description: 'House-made lemonade with mint and a hint of ginger',
    category: 'beverage',
    price: 5.99,
    isAvailable: true,
    isVeg: true,
    calories: 120,
    prepTime: 5,
    image: 'https://images.unsplash.com/photo-1523677011781-c91d1bbe2f66?w=400&h=300&fit=crop',
  },
  {
    id: '15',
    name: 'Espresso',
    description: 'Double shot of premium espresso',
    category: 'beverage',
    price: 3.99,
    isAvailable: true,
    isVeg: true,
    calories: 10,
    prepTime: 3,
    image: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?w=400&h=300&fit=crop',
  },
  {
    id: '16',
    name: 'Iced Tea',
    description: 'Freshly brewed iced tea with lemon',
    category: 'beverage',
    price: 4.99,
    isAvailable: true,
    isVeg: true,
    calories: 80,
    prepTime: 3,
    image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=300&fit=crop',
  },
];
